# Step 1: Build the React app
FROM node:18 AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Step 2: Serve it with NGINX
FROM nginx:1.21.0-alpine
COPY --from=builder /app/build /usr/share/nginx/html
