version: '3.9'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env  # contains DATABASE_URL pointing to Supabase
    ports:
      - "8080:8080"
    networks:
      - bible-net

  frontend:
    build: ./frontend
    ports:
      - "3000:8080"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - bible-net

networks:
  bible-net:
