name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Ensure Docker uses gcloud's authentication for Artifact Registry
      - name: Configure Docker authentication for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image to Artifact Registry
        run: |
          IMAGE_URI="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-bible-app-repo/my-bible-api:${{ github.sha }}"
          echo "Building Docker image: $IMAGE_URI"
          docker build -t "$IMAGE_URI" ./backend
          echo "Pushing Docker image: $IMAGE_URI"
          docker push "$IMAGE_URI"

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URI="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-bible-app-repo/my-bible-api:${{ github.sha }}"
          echo "Deploying to Cloud Run with image: $IMAGE_URI"
          gcloud run deploy my-bible-api \
            --image "$IMAGE_URI" \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
